version: '3'

services:
  bot:
    build: .
    container_name: 3d-telegram-bot
    restart: always
    environment: 
      - BOT_TOKEN=${BOT_TOKEN}
      - PG_CONNECTION_STRING=${PG_CONNECTION_STRING}
      - QUEUE_CONNECTION_STRING=${QUEUE_CONNECTION_STRING}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CONNECTION_STRING=${CONNECTION_STRING}
    command: node server.js